### ISSUE TITLE
Innovative question

### ISSUE THREAD

**Issue by Fucapisun** [OSUPCVLab/SegFormer3D#1]
How do you design a model for 2D images into a design idea for 3D images

**Comment by bnavard** [comment]
This is a broad question  and not quite relevant to this repository. Nevertheless, depending on your architecture it can vary. For example see this [tutorial](https://towardsdatascience.com/2d-or-3d-a-simple-comparison-of-convolutional-neural-networks-for-automatic-segmentation-of-625308f52aa7).
