### ISSUE TITLE
how to train my own dataset?

### ISSUE THREAD

**Issue by wydilearn** [OSUPCVLab/SegFormer3D#12]
I can not preprocess the dataset using providing codes. Please provide full explicit comments for how to use other datset.

**Comment by wydilearn** [comment]
My terminal only print the two sentences without doing anything:
"started preprocessing Brats2017..."
"finished preprocessing Brats2017..."
Is this a incomplete codes?

**Comment by bnavard** [comment]
The preprocessing code only processes Brats dataset. What is your dataset ?

**Comment by wydilearn** [comment]
My dataset has only one channel, and I have transform my dataset correctly, but I still cannot train the dataset. Could you please explain which part of the codes that I need to edit?

**Comment by wydilearn** [comment]
In addition, my labels have three classes.

**Comment by wydilearn** [comment]
And my image size is 128*48*96

**Comment by wydilearn** [comment]
And my image size is 128x48x96

**Comment by wydilearn** [comment]
![无标题](https://github.com/user-attachments/assets/5f141c3e-adff-438e-9390-a8c227f28004)
In addition, I don't find the test codes. I can not test the model after training it.

**Comment by i-mein** [comment]
> If your dataset is BraTS you can use our datapreprcoessing. What is your dataset ? If you are using a data with different shape (other than 128x128x128) you need to change the SegFormer3D architecture config such that the path embeddings works with your dataset size. For that you should change your experiment config.

hello, thanks for creating and maintaining this repo! 

for e.g. could you suggest what changes should be made for a dataset with shape `(D, X, Y)=(32, 128, 128)` ?

```
embed_dims: list = [32, 64, 160, 256],
patch_kernel_size: list = [7, 3, 3, 3],
patch_stride: list = [4, 2, 2, 2],
patch_padding: list = [3, 1, 1, 1],
```

If I understand correct the above lists correspond to i-th MixViT block operations uniform for x,y,z dims
