### ISSUE TITLE
how do you train on both the Automated Cardiac Diagnosis Dataset (ACDC) and Multi-Organ CT Segmentation Dataset (Synapse)?

### ISSUE THREAD

**Issue by 1024AILab** [OSUPCVLab/SegFormer3D#2]
Thanks for your work; how do you train on both the Automated Cardiac Diagnosis Dataset (ACDC) and Multi-Organ CT Segmentation Dataset (Synapse)? Can you provide me the code for the dataloader? I would appreciate it.

**Comment by bnavard** [comment]
Thanks for having interest in our repo. We will provide the details soon. Please watch our repo for this sake.
