### ISSUE TITLE
evaluate error

### ISSUE THREAD

**Issue by Zhihao-chen-666** [OSUPCVLab/SegFormer3D#4]
![e816438e1cd13f5faff122be0de7e49](https://github.com/OSUPCVLab/SegFormer3D/assets/39455680/2f45e11c-d627-4857-b4e3-c479bfe06c60)
After the training is done, test reports an error. Also I can't use accelerate launch --config_file . /gpu_accelerate.yaml run_experiment.py command, I use python run_experiment.py instead for launch.

**Comment by srperera** [comment]
hi yes we left that function incomplete because we realized it was easier to manually test the models performance in a jupyter notebook than building it into the trainer. This way we can easily visualize things as needed.
