### ISSUE TITLE
Could you provide the test code?

### ISSUE THREAD

**Issue by sanny1226** [OSUPCVLab/SegFormer3D#5]
Thanks for your good work. It looks like a lightweight model for medical image segmentation.
I would like to use it on clinical data.
Could you please provide some preprocessing and the testing code, especially for the clinical MRI data segmentation.
Thanks so much.

**Comment by srperera** [comment]
Hi we used the exact testing technique from this well known repo to help keep things consistent.
https://github.com/282857341/nnFormer
